{% set name = "riscv-tools" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  number: {{ build_number }}
  string: {{ [build_number, ('h' + PKG_HASH), environ.get('GIT_DESCRIBE_HASH', '')]|join('_') }}
  skip: True # [not linux64]
  # needed to avoid overlinking errors
  missing_dso_whitelist:
    - '*'
  # needed to avoid unable to find specs files errors
  detect_binary_files_with_prefix: False
  # list out areas where conda can use patchelf (ignore the sysroot)
  binary_relocation:
    - 'riscv-tools/bin/**'
    - 'riscv-tools/include/**'
    - 'riscv-tools/lib/**'
    - 'riscv-tools/libexec/**'
    - 'riscv-tools/riscv64-unknown-elf/**'
    - 'riscv-tools/riscv64-unknown-linux-gnu/**'
    - 'riscv-tools/share/**'

requirements:
  build:
    # toolchain deps
    - gcc>=10
    - gxx>=10
    - conda-gcc-specs
    - gawk
    - sysroot_linux-64 2.17 # [linux64]
    # if building riscv-toolchain from source, we need to use bison=3.4 until we have
    # https://github.com/riscv-collab/riscv-binutils-gdb/commit/314ec7aeeb1b2e68f0d8fb9990f2335f475a6e33
    - bison==3.4.*
    - patch
    - git
    - make
    - dtc
    - binutils
    - texinfo
    - python
    - autoconf
    - automake
    - flex
    - libtool
    - zlib
    #- host:
    - expat
    - ncurses
    - gmp
    - mpfr
    - mpc
    #- zlib
    - file
  ignore_run_exports_from:
    # nothing links against libpython, the build scripts just don't work out
    # of the box if you split the libs into build/host
    - python

test:
  commands:
    - test "$($PREFIX/riscv-tools/bin/riscv64-unknown-elf-gcc -dumpversion)" = "12.2.0"

about:
  home: https://github.com/ucb-bar/riscv-tools-feedstock
  summary: RISC-V toolchain for UC Berkeley projects

extra:
  recipe-maintainers:
    - abejgonzalez
